#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Peak\Climber\Application;
use Peak\Climber\Cron\RegisterCommands;
use Cli\Commands\ExampleCommand;

try {
    // create cli application
    $application = new Application(null, [
        'env' => 'dev',
        'conf' => [
            __DIR__.'/config/cli.php',
            __DIR__.'/config/cron.database.php'
        ]
    ]);

    // register cron commands
    new RegisterCommands($application);

    // register other commands
    $application->add(new ExampleCommand());

    // and finally, run the whole thing
    $application->run();

} catch(Exception $e) {
    echo get_class($e).': '.$e->getMessage();
}
