app:
  name: Peak App
  version: 1.0

php:
  display_errors: 0
  display_startup_errors: 0
  date.timezone: America/Toronto

session:
  options:
    cookie_httponly: 1
    cookie_secure: 1

routes_path_prefix: /peakphp/peak/public
routes:
  - path: /welcome
    stack: \App\Controller\HomeController